server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route1          #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**    #断言，路径相匹配的进行路由
            #- After=2022-01-13T16:38:21.608+08:00[Asia/Shanghai]
            #- Before=2022-01-31T16:38:21.608+08:00[Asia/Shanghai]
            - Between=2022-01-13T16:38:21.608+08:00[Asia/Shanghai],2022-01-31T16:38:21.608+08:00[Asia/Shanghai]
            #- Cookie=username,sg
            #- #Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性并且值为正整数的正则表达式
            #- Host=**.atguigu.com
            - Method=GET
            #- Query=username, \d+  # 要有参数名username并且值为正整数才能路由
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id，值为1024

        - id: payment_route2          #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**     #断言，路径相匹配的进行路由
            #- After=2022-01-13T16:38:21.608+08:00[Asia/Shanghai]
            #- Before=2022-01-31T16:38:21.608+08:00[Asia/Shanghai]
            - Between=2022-01-13T16:38:21.608+08:00[Asia/Shanghai],2022-01-31T16:38:21.608+08:00[Asia/Shanghai]
            #- Cookie=username,sg
            #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性并且值为正整数的正则表达式
            #- Host=**.atguigu.com
            - Method=GET
            #- Query=username, \d+  # 要有参数名username并且值为正整数才能路由
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id，值为1024

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #注册到eureka服务列表中
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka