server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        #配置Nacos地址
        #server-addr: localhost:8848 #单机版
        server-addr: 192.168.160.22:1111 #集群版

# 消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://nacos-payment-provider

