server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    #表示是否将自己注册进EurekaServer，默认为true。false表示不向注册中心注册自己
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true。false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
      #defaultZone: http://eureka7001.com:7001/eureka # 单机版
  #server:
    #关闭自我保护机制，保证不可用服务被及时踢除，默认为true
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 2000 #心跳时间间隔（单位为毫秒）